# Generated by Django 5.1.7 on 2025-07-11 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_remove_feedbackresponse_response_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LatexDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('tex_file', models.FileField(upload_to='latex_docs/')),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
    ]
